// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualPeer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddManualPeer'](arg1, arg2, arg3);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckFileMessageAvailable(arg1) {
  return window['go']['main']['App']['CheckFileMessageAvailable'](arg1);
}

export function ChooseDataDirectory() {
  return window['go']['main']['App']['ChooseDataDirectory']();
}

export function CleanupUnusedMedia() {
  return window['go']['main']['App']['CleanupUnusedMedia']();
}

export function ClearConversation(arg1) {
  return window['go']['main']['App']['ClearConversation'](arg1);
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function DataPath() {
  return window['go']['main']['App']['DataPath']();
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function EnsureDebugPeer() {
  return window['go']['main']['App']['EnsureDebugPeer']();
}

export function LoadConversationPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoadConversationPage'](arg1, arg2, arg3, arg4);
}

export function LoadFileSource(arg1, arg2) {
  return window['go']['main']['App']['LoadFileSource'](arg1, arg2);
}

export function LoadImageSource(arg1, arg2) {
  return window['go']['main']['App']['LoadImageSource'](arg1, arg2);
}

export function LoadStorageStats() {
  return window['go']['main']['App']['LoadStorageStats']();
}

export function OpenFileMessage(arg1) {
  return window['go']['main']['App']['OpenFileMessage'](arg1);
}

export function RetryMessage(arg1, arg2) {
  return window['go']['main']['App']['RetryMessage'](arg1, arg2);
}

export function RevealFileMessage(arg1) {
  return window['go']['main']['App']['RevealFileMessage'](arg1);
}

export function RevealImageMessage(arg1) {
  return window['go']['main']['App']['RevealImageMessage'](arg1);
}

export function SaveFileMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileMessage'](arg1, arg2, arg3);
}

export function SaveImageMessage(arg1, arg2) {
  return window['go']['main']['App']['SaveImageMessage'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SendFileMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFileMessage'](arg1, arg2, arg3);
}

export function SendImageMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendImageMessage'](arg1, arg2, arg3);
}

export function SendLocalFileMessage(arg1, arg2) {
  return window['go']['main']['App']['SendLocalFileMessage'](arg1, arg2);
}

export function SetUnreadCount(arg1) {
  return window['go']['main']['App']['SetUnreadCount'](arg1);
}

export function UpdateDisplayName(arg1) {
  return window['go']['main']['App']['UpdateDisplayName'](arg1);
}

export function UpdateLanguage(arg1) {
  return window['go']['main']['App']['UpdateLanguage'](arg1);
}

export function UpdateTheme(arg1) {
  return window['go']['main']['App']['UpdateTheme'](arg1);
}
