// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function Bootstrap():Promise<chat.Snapshot>;

export function ChooseDataDirectory():Promise<string>;

export function DataPath():Promise<string>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function UpdateDisplayName(arg1:string):Promise<chat.Profile>;

export function UpdateLanguage(arg1:string):Promise<chat.Settings>;
