// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function ChooseDataDirectory() {
  return window['go']['main']['App']['ChooseDataDirectory']();
}

export function DataPath() {
  return window['go']['main']['App']['DataPath']();
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function UpdateDisplayName(arg1) {
  return window['go']['main']['App']['UpdateDisplayName'](arg1);
}

export function UpdateLanguage(arg1) {
  return window['go']['main']['App']['UpdateLanguage'](arg1);
}
